service: ippo-server
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: dev1
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
